In [1]:
import pandas as pd
import numpy as np

In [ ]:
c = np.array([
    [0,     1,     1],
    [1,     0,     1],
    [1,     1,     0],
])
c

array([[10.,  1.,  1., inf],
       [ 1., 10.,  1.,  1.],
       [ 1.,  1., 10.,  1.],
       [inf, inf, inf, inf]])

In [4]:
w = np.exp(-1 * c)
w

array([[4.53999298e-05, 3.67879441e-01, 3.67879441e-01, 0.00000000e+00],
       [3.67879441e-01, 4.53999298e-05, 3.67879441e-01, 3.67879441e-01],
       [3.67879441e-01, 3.67879441e-01, 4.53999298e-05, 3.67879441e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [5]:
eigan_values = np.linalg.eigvals(w)
eigan_values

array([-0.36783404,  0.73580428, -0.36783404,  0.        ])